CREATE TABLE DATE
(
	ID INT,
	YEAR_ID INT,
	MONTH_ID INT
);
CREATE TABLE HOME
(
	ID INT PRIMARY KEY NOT NULL IDENTITY,
	USER_ID INT,
	ADDRES VARCHAR(50),
	ROW_STATUS INT DEFAULT 0 NOT NULL
);
CREATE TABLE HOME_SERVICES
(
	ID INT PRIMARY KEY NOT NULL IDENTITY,
	HOME_ID INT,
	SERVICE_ID INT,
	ROW_STATUS INT DEFAULT 0 NOT NULL
);
CREATE TABLE HOME_SERVICES_ACCOUNTS
(
	ID INT PRIMARY KEY NOT NULL IDENTITY,
	HOME_SERVICES_ID INT,
	ACCOUNT VARCHAR(20),
	ROW_STATUS INT DEFAULT 0 NOT NULL
);
CREATE TABLE PAYMENTS
(
	ID INT PRIMARY KEY NOT NULL IDENTITY,
	HOME_SERVICES_ACCOUNTS_ID INT,
	DATE_ID INT,
	TARIFF FLOAT,
	INVOICE FLOAT,
	DATE_PAID DATETIME,
	ACTIVE_TARIFF BIT DEFAULT 0 NOT NULL,
	ROW_STATUS INT DEFAULT 0 NOT NULL
);
CREATE TABLE SERVICES
(
	ID INT PRIMARY KEY NOT NULL IDENTITY,
	NAME VARCHAR(100),
	ROW_STATUS INT DEFAULT 0 NOT NULL
);
CREATE TABLE USERS
(
	ID INT PRIMARY KEY NOT NULL IDENTITY,
	LAST_NAME VARCHAR(50),
	FIRST_NAME VARCHAR(50),
	EMAIL VARCHAR(50),
	PASSWORD VARCHAR(20),
	ROW_STATUS INT DEFAULT 0 NOT NULL
);